### See helm stable chart to apply other settings of MYSQL.
### Link : https://github.com/helm/charts/tree/master/stable/mysql
mysql:
  enable: true
  # docker image
  image: "pinpointdocker/pinpoint-mysql"
  # tag
  imageTag: "2.1.0"

  ## Specify password for root user
  ## Default: random 10 character string
  mysqlRootPassword: root123

  ## Create a database user
  mysqlUser: admin

  ## Default: random 10 character string
  mysqlPassword: admin

  ## Create a database
  mysqlDatabase: pinpoint

  ## Extra Initial Script
  # initializationFiles:     
  #   extra_init.sql: |-
  #     CREATE TABLE ...